language: java

addons:
  sonarcloud:
    organization: "altod69-github"

script:
  # JaCoCo is used to have code coverage, the agent has to be activated
   - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.projectKey=altod69_ipi-java-350-ex

